<?php
/** @var $block \Maisondunet\SaveQuote\Block\ListSavedQuote */
/** @var $escaper \Magento\Framework\Escaper */

/** @var \Magento\Framework\Data\Helper\PostHelper $dataPosthelper */
$dataPosthelper = $this->helper(\Magento\Framework\Data\Helper\PostHelper::class);
?>
<h2><?= __("List of your saved carts") ?></h2>

<?php
$result = $block->getCustomerSavedCartList();
if ($result === null || $result->getTotalCount() === 0): ?>
<p><?=__("There is no saved cart")?></p>

<?php else: ?>

<table class="data table">
    <thead>
    <tr>
        <th class="col"><?=__("Name")?></th>
        <th class="col"><?=__("Description")?></th>
        <th class="col"><?=__("Number of Items")?></th>
        <th class="col"><?=__("Total price")?></th>
        <th class="col"><?=__("Action")?></th>
    </tr>
    </thead>
    <tbody>

    <?php foreach ($result->getItems() as $item): ?>
    <tr>
        <td class="col"><?= $item->getName() ?></td>
        <td class="col"><?= $item->getDescription() ?></td>
        <td class="col"><?= $item->getItemsCount() ?></td>
        <td class="col"><?= $block->getFormatedPrice($item->getGrandTotal()) ?></td>
        <td class="col">

            <div style="display: inline-block">
                <?php
                /** @var \Maisondunet\SaveQuote\Block\Button\ButtonAction $button */
                $button = $block->getChildBlock('mdn.button.action.view');
                $button->setQuoteDescription($item);
                ?>
                <?= $button->toHtml() ?>
                <?php
                /** @var \Maisondunet\SaveQuote\Block\Button\ButtonAction $button */
                $button = $block->getChildBlock('mdn.button.action.restore');
                $button->setQuoteDescription($item);
                ?>
                <?= $button->toHtml() ?>
                <?php
                /** @var \Maisondunet\SaveQuote\Block\Button\ButtonAction $button */
                $button = $block->getChildBlock('mdn.button.action.delete');
                $button->setQuoteDescription($item);
                ?>
                <?= $button->toHtml() ?>
            </div>

        </td>
    </tr>
    </tbody>
    <?php endforeach;
    endif; ?>
</table>
