<?php
/** @var $block \Maisondunet\SaveQuote\Block\SaveQuote */
?>
<h2>List of your saved carts</h2>
<table class="data table">
    <thead>
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Number of Items</th>
        <th>Total price</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <?php
    $result = $block->getCustomerSaveCart();
    if ($result === null || $result->getTotalCount() === 0): ?>
        <p>Vous n'avez aucun panier sauvegardé</p>
    <?php else:
    foreach ($result->getItems() as $item): ?>
    <tr>
        <td><?= $item->getName() ?></td>
        <td><?= $item->getDescription() ?></td>
        <td><?= $item->getItemsCount() ?></td>
        <td><?= $block->getFormatedPrice($item->getGrandTotal()) ?></td>
        <td>
            <form method="post" action="/mdnsavecart/customer/switchcart">
                <input type="hidden" value="<?= $item->getQuoteId() ?>" name="quote_id">
                <button type="submit">Add active cart</button>
            </form>
            <form method="post" action="/mdnsavecart/customer/delete">
                <input type="hidden" value="<?= $item->getQuoteDescriptionId() ?>" name="entity_id">
                <button type="submit">Delete</button>
            </form>
        </td>
    </tr>
    </tbody>
    <?php endforeach;
    endif; ?>
</table>
