<?php
/** @var $block \Maisondunet\SaveQuote\Block\ListSavedQuote */
/** @var $escaper \Magento\Framework\Escaper */

/** @var \Magento\Framework\Data\Helper\PostHelper $dataPosthelper */
$dataPosthelper = $this->helper(\Magento\Framework\Data\Helper\PostHelper::class);
?>
<h2><?= __("List of your saved carts") ?></h2>

<?php
$result = $block->getCustomerSavedCartList();
if ($result === null || $result->getTotalCount() === 0): ?>
<p><?=__("There is no saved cart")?></p>

<?php else: ?>

<table class="data table">
    <thead>
    <tr>
        <th class="col"><?=__("Name")?></th>
        <th class="col"><?=__("Description")?></th>
        <th class="col"><?=__("Number of Items")?></th>
        <th class="col"><?=__("Total price")?></th>
        <th class="col"><?=__("Action")?></th>
    </tr>
    </thead>
    <tbody>

    <?php foreach ($result->getItems() as $item): ?>
    <tr>
        <td class="col"><?= $item->getName() ?></td>
        <td class="col"><?= $item->getDescription() ?></td>
        <td class="col"><?= $item->getItemsCount() ?></td>
        <td class="col"><?= $block->getFormatedPrice($item->getGrandTotal()) ?></td>
        <td class="col">

            <div style="display: inline-block">
                <a class="action cart" href="#"
                   data-post="<?= $escaper->escapeHtmlAttr($block->getAddActivePostData($item)) ?>"><?=__("Add active cart")?></a>
                <span>|</span>
                <a class="action cart" href=<?= $escaper->escapeHtmlAttr($block->getAddViewProductDetail($item->getQuoteDescriptionId())) ?>><?= __("View") ?></a>
                <span>|</span>
                <a class="action cart" href="#"
                   data-post="<?= $escaper->escapeHtmlAttr($block->getAddDeletePostData($item)) ?>"><?= __("Delete") ?></a>
            </div>

        </td>
    </tr>
    </tbody>
    <?php endforeach;
    endif; ?>
</table>
