<?php /** @var $block \Maisondunet\SaveQuote\Block\SaveQuote */?>

<div class="popup-modal" style="display: none">
    <form method="post" action="/mdnsavecart/savecart"  class="popup-form-data-submit">
        <p>Your cart is not save if you switch now you lose it</p>
        <label for="name" id="name">Name</label>
        <input type="text" name="name">
        <label for="description" id="description">Description</label>
        <input type="text" name="description" id="description">
        <input type="hidden" name="quote_id" value="<?php try {
            echo $block->getActiveQuote();
        } catch (\Magento\Framework\Exception\NoSuchEntityException $e) {
        } ?>">
        <button type="submit">Save</button>
    </form>
</div>
<script type="text/x-magento-init">
     {
        "*": {
            "Maisondunet_SaveQuote/js/popup-form": { }
        }
    }
</script>
