<?php
/** @var $block \Maisondunet\SaveQuote\Block\SaveQuote */
/** @var $escaper \Magento\Framework\Escaper  */

use Magento\Customer\Model\Url;


?>
<div id="popup-content">
    <?= $block->getChildHtml('mdn_popup_form_block') ?>
</div>

<?php if ($block->userIsLoggedIn()): ?>
    <button id="popup-form-button" data-mage-init="<?= $escaper->escapeHtmlAttr(json_encode(["popup-form" => ["target" => "#popup-content"]]))?>">
        <?= __("Save Your Cart") ?>
    </button>
<?php else: ?>
    <a class="button" href="<?= $block->getUrl("customer/account/login", [Url::REFERER_QUERY_PARAM_NAME => base64_encode($block->getUrl("checkout/cart"))]) ?>">
        <?= __("Save Your Cart") ?>
    </a>

<?php endif; ?>


<script type="text/javascript">
    require([
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function ($, modal) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Save Your Cart',
                buttons: [{
                    text: $.mage.__('Close'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };


            var popup = modal(options, $('#popup-content'));

            $('#popup-form-button').on('click', function () {
                $('#popup-content').modal('openModal');
            });
        })
</script>
